# -*- coding: utf-8 -*-
"""Import To Supabase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFci6lKKXw_7a1PHGy8mhxW9ikNoiWAi
"""

!pip install python-dotenv faiss-cpu supabase

from google.colab import drive
drive.mount('/content/drive')

import json
import numpy as np
import pandas as pd
from tqdm import tqdm
import requests
import time
from sentence_transformers import SentenceTransformer
import pickle
import os
from typing import List, Dict, Any, Optional, Union
import re
import google.colab
from google.colab import drive
from supabase import create_client, Client
import os
import dotenv

class MTGCardEmbedder:
    def __init__(self,
                 model_name: str = "all-MiniLM-L6-v2",
                 embedding_dim: int = 384,
                 data_path: str = "/content/drive/MyDrive/MTGData",
                 use_supabase: bool = True):
        """
        Initialize the MTG Card Embedder with Google Colab and Supabase support

        Args:
            model_name: Name of the sentence-transformer model to use
            embedding_dim: Dimension of embeddings
            data_path: Path to store local data (default: Google Drive MTGData folder)
            use_supabase: Whether to use Supabase for data storage
        """
        # Mount Google Drive if not already mounted
        try:
            drive.mount('/content/drive', force_remount=False)
            print("Google Drive mounted successfully")
        except:
            print("Google Drive already mounted or could not be mounted")

        self.model = SentenceTransformer(model_name)
        self.embedding_dim = embedding_dim
        self.data_path = data_path
        self.use_supabase = use_supabase

        # Initialize Supabase if needed
        if self.use_supabase:
            try:
                # Try to load from .env file first
                dotenv.load_dotenv()

                # Get Supabase credentials
                self.supabase_url = os.getenv('SUPABASE_URL', 'https://hvsbfeyufrzmohzxsbcq.supabase.co')
                self.supabase_key = os.getenv('SUPABASE_KEY')

                # If not found in env, prompt user for key
                if not self.supabase_key:
                    from getpass import getpass
                    print("Supabase key not found in environment variables.")
                    self.supabase_key = getpass("Enter your Supabase API key: ")

                # Initialize Supabase client
                self.supabase = create_client(self.supabase_url, self.supabase_key)
                print("Supabase client initialized successfully")
            except Exception as e:
                print(f"Error initializing Supabase: {e}")
                print("Falling back to local storage only")
                self.use_supabase = False

        # Ensure data directory exists in Google Drive
        os.makedirs(data_path, exist_ok=True)

        # Initialize containers
        self.card_dict = {}
        self.embeddings = {}
        self.price_data = {}
        self.price_embeddings = {}

    def fetch_all_sets(self) -> List[Dict]:
        """Fetch all set data from Scryfall"""
        print("Fetching all sets from Scryfall...")

        response = requests.get("https://api.scryfall.com/sets")
        if response.status_code != 200:
            print(f"Error fetching sets: {response.status_code}")
            return []

        sets_data = response.json()
        return sets_data.get('data', [])

    def fetch_all_cards_by_set(self) -> Dict:
        """Fetch all cards organized by set"""
        print("Fetching cards from all sets...")

        # Get all sets first
        all_sets = self.fetch_all_sets()
        print(f"Found {len(all_sets)} sets")

        cards = {}
        card_count = 0

        # Process each set
        for set_data in all_sets:
            set_code = set_data.get('code')
            set_name = set_data.get('name')
            search_uri = set_data.get('search_uri')

            if not search_uri:
                continue

            print(f"Fetching cards from {set_name} ({set_code})...")

            # Use the search URI to get all cards in the set
            url = search_uri
            set_cards = 0

            while url:
                print(f"  Processing page: {url}")

                # Add delay to avoid rate limiting
                time.sleep(0.1)

                try:
                    response = requests.get(url)

                    # Handle rate limiting with exponential backoff
                    retries = 0
                    while response.status_code == 429 and retries < 5:
                        retry_after = int(response.headers.get('Retry-After', 1))
                        wait_time = retry_after * (2 ** retries)
                        print(f"Rate limited. Waiting {wait_time} seconds...")
                        time.sleep(wait_time)
                        response = requests.get(url)
                        retries += 1

                    if response.status_code != 200:
                        print(f"Error fetching data: {response.status_code}")
                        break

                    data = response.json()

                    # Process cards in this page
                    for card in data.get('data', []):
                        card_id = card.get('id')

                        # Skip cards without IDs
                        if not card_id:
                            continue

                        cards[card_id] = {
                            'id': card_id,
                            'name': card.get('name', ''),
                            'type_line': card.get('type_line', ''),
                            'oracle_text': card.get('oracle_text', ''),
                            'mana_cost': card.get('mana_cost', ''),
                            'cmc': card.get('cmc', 0),
                            'color_identity': card.get('color_identity', []),
                            'keywords': card.get('keywords', []),
                            'image_uris': card.get('image_uris', {}),
                            'legalities': card.get('legalities', {}),
                            'prices': card.get('prices', {}),
                            'rarity': card.get('rarity', '')
                        }
                        set_cards += 1

                    # Check if there's another page
                    url = data.get('next_page')

                except Exception as e:
                    print(f"Error processing set {set_code}: {e}")
                    break

            print(f"  Added {set_cards} cards from {set_name}")
            card_count += set_cards

        self.card_dict = cards
        print(f"Fetched {card_count} cards from {len(all_sets)} sets")

        # Save to Supabase (batched to avoid size limitations)
        if self.use_supabase:
            self._save_cards_to_supabase(cards)

        # Also save locally as backup
        with open(f"{self.data_path}/card_data.json", 'w') as f:
            json.dump(cards, f)

        return cards

    def _save_cards_to_supabase(self, cards: Dict) -> None:
        """Save cards to Supabase in batches"""
        print("Saving cards to Supabase...")

        # Convert dictionary to list for easier batching
        card_list = []
        for card_id, card_data in cards.items():
            # Convert to format for database insertion
            db_card = {
                'id': card_id,
                'name': card_data.get('name', ''),
                'type_line': card_data.get('type_line', ''),
                'oracle_text': card_data.get('oracle_text', ''),
                'mana_cost': card_data.get('mana_cost', ''),
                'cmc': card_data.get('cmc', 0),
                'color_identity': json.dumps(card_data.get('color_identity', [])),
                'keywords': json.dumps(card_data.get('keywords', [])),
                'image_uris': json.dumps(card_data.get('image_uris', {})),
                'legalities': json.dumps(card_data.get('legalities', {})),
                'prices': json.dumps(card_data.get('prices', {})),
                'rarity': card_data.get('rarity', '')
            }
            card_list.append(db_card)

        # Insert in batches of 100
        batch_size = 100
        total_batches = (len(card_list) + batch_size - 1) // batch_size  # Ceiling division

        for i in tqdm(range(0, len(card_list), batch_size), desc="Uploading card batches", total=total_batches):
            batch = card_list[i:i+batch_size]

            try:
                # Upsert data (insert or update if exists)
                result = self.supabase.table('mtg_cards').upsert(batch).execute()

                # Check for errors
                if hasattr(result, 'error') and result.error:
                    print(f"Error in batch {i//batch_size + 1}: {result.error}")
            except Exception as e:
                print(f"Failed to upload batch {i//batch_size + 1}: {e}")

    def extract_price_data(self) -> Dict:
        """Extract price data from cards and store separately"""
        print("Extracting price data...")

        price_data = {}

        for card_id, card_info in tqdm(self.card_dict.items()):
            prices = card_info.get('prices', {})

            price_data[card_id] = {
                'name': card_info.get('name', ''),
                'usd': prices.get('usd'),
                'usd_foil': prices.get('usd_foil'),
                'usd_etched': prices.get('usd_etched'),
                'eur': prices.get('eur'),
                'tix': prices.get('tix')
            }

        self.price_data = price_data

        # Save to Supabase
        if self.use_supabase:
            self._save_prices_to_supabase(price_data)

        # Save locally as well
        with open(f"{self.data_path}/price_data.json", 'w') as f:
            json.dump(price_data, f)

        return price_data

    def _save_prices_to_supabase(self, price_data: Dict) -> None:
        """Save price data to Supabase in batches"""
        print("Saving price data to Supabase...")

        # Convert dictionary to list
        price_list = []
        for card_id, price_info in price_data.items():
            db_price = {
                'card_id': card_id,
                'name': price_info.get('name', ''),
                'usd': price_info.get('usd'),
                'usd_foil': price_info.get('usd_foil'),
                'usd_etched': price_info.get('usd_etched'),
                'eur': price_info.get('eur'),
                'tix': price_info.get('tix'),
                'updated_at': time.strftime('%Y-%m-%d %H:%M:%S')  # Timestamp for tracking
            }
            price_list.append(db_price)

        # Insert in batches of 100
        batch_size = 100
        total_batches = (len(price_list) + batch_size - 1) // batch_size

        for i in tqdm(range(0, len(price_list), batch_size), desc="Uploading price batches", total=total_batches):
            batch = price_list[i:i+batch_size]

            try:
                # Upsert data
                result = self.supabase.table('mtg_prices').upsert(batch).execute()

                if hasattr(result, 'error') and result.error:
                    print(f"Error in batch {i//batch_size + 1}: {result.error}")
            except Exception as e:
                print(f"Failed to upload price batch {i//batch_size + 1}: {e}")

    def create_price_embeddings(self) -> Dict:
        """Create vector embeddings specifically for price ranges"""
        print("Creating price embeddings...")

        price_embeddings = {}

        # Define price ranges for vectorization
        price_ranges = [
            (0, 0),       # Unknown/Zero
            (0.01, 1),    # Budget
            (1, 5),       # Affordable
            (5, 20),      # Moderate
            (20, 50),     # Premium
            (50, 1000)    # High-end
        ]

        embedding_dim = len(price_ranges)

        for card_id, price_info in tqdm(self.price_data.items()):
            # Get USD price (or default to 0)
            usd_price = 0
            if price_info['usd']:
                try:
                    usd_price = float(price_info['usd'])
                except (ValueError, TypeError):
                    usd_price = 0

            # Create a one-hot encoding based on price range
            embedding = np.zeros(embedding_dim)

            for i, (min_price, max_price) in enumerate(price_ranges):
                if min_price <= usd_price <= max_price:
                    embedding[i] = 1
                    break

            price_embeddings[card_id] = embedding

        self.price_embeddings = price_embeddings

        # Save to Supabase
        if self.use_supabase:
            self._save_price_embeddings_to_supabase(price_embeddings)

        # Save locally as well
        with open(f"{self.data_path}/price_embeddings.pkl", 'wb') as f:
            pickle.dump(price_embeddings, f)

        return price_embeddings

    def _save_price_embeddings_to_supabase(self, price_embeddings: Dict) -> None:
        """Save price embeddings to Supabase"""
        print("Saving price embeddings to Supabase...")

        # Convert dictionary to list
        embedding_list = []
        for card_id, embedding in price_embeddings.items():
            db_embedding = {
                'card_id': card_id,
                'embedding': embedding.tolist(),  # Convert numpy array to list
                'updated_at': time.strftime('%Y-%m-%d %H:%M:%S')
            }
            embedding_list.append(db_embedding)

        # Insert in batches
        batch_size = 100
        total_batches = (len(embedding_list) + batch_size - 1) // batch_size

        for i in tqdm(range(0, len(embedding_list), batch_size), desc="Uploading price embedding batches", total=total_batches):
            batch = embedding_list[i:i+batch_size]

            try:
                # Upsert data
                result = self.supabase.table('mtg_price_embeddings').upsert(batch).execute()

                if hasattr(result, 'error') and result.error:
                    print(f"Error in batch {i//batch_size + 1}: {result.error}")
            except Exception as e:
                print(f"Failed to upload price embedding batch {i//batch_size + 1}: {e}")

    def prepare_text_for_embedding(self, card_info: Dict) -> str:
        """Prepare card text for embedding by combining relevant fields"""
        text_parts = []

        # Add card name
        text_parts.append(f"Name: {card_info.get('name', '')}")

        # Add mana cost if available
        if 'mana_cost' in card_info and card_info['mana_cost']:
            text_parts.append(f"Mana Cost: {card_info['mana_cost']}")

        # Add type line
        if 'type_line' in card_info and card_info['type_line']:
            text_parts.append(f"Type: {card_info['type_line']}")

        # Add oracle text
        if 'oracle_text' in card_info and card_info['oracle_text']:
            text_parts.append(f"Text: {card_info['oracle_text']}")

        # Add keywords
        if 'keywords' in card_info and card_info['keywords']:
            text_parts.append(f"Keywords: {', '.join(card_info['keywords'])}")

        # Add color identity
        if 'color_identity' in card_info and card_info['color_identity']:
            text_parts.append(f"Colors: {', '.join(card_info['color_identity'])}")

        return " ".join(text_parts)

    def create_card_embeddings(self) -> Dict:
        """Create vector embeddings for all cards based on their text"""
        print("Creating card embeddings...")

        embeddings = {}

        # Prepare the text for all cards
        texts = []
        card_ids = []

        for card_id, card_info in tqdm(self.card_dict.items(), desc="Preparing texts"):
            card_text = self.prepare_text_for_embedding(card_info)
            texts.append(card_text)
            card_ids.append(card_id)

        # Create embeddings in batches to avoid OOM errors in Colab
        batch_size = 64  # Smaller batch size for Colab
        for i in tqdm(range(0, len(texts), batch_size), desc="Generating embeddings"):
            batch_texts = texts[i:i+batch_size]
            batch_ids = card_ids[i:i+batch_size]

            # Generate embeddings
            batch_embeddings = self.model.encode(batch_texts)

            # Store embeddings
            for j, card_id in enumerate(batch_ids):
                embeddings[card_id] = batch_embeddings[j]

        self.embeddings = embeddings

        # Save to Supabase
        if self.use_supabase:
            self._save_card_embeddings_to_supabase(embeddings)

        # Save locally as well
        with open(f"{self.data_path}/card_embeddings.pkl", 'wb') as f:
            pickle.dump(embeddings, f)

        return embeddings

    def _save_card_embeddings_to_supabase(self, embeddings: Dict) -> None:
        """Save card embeddings to Supabase"""
        print("Saving card embeddings to Supabase...")

        # Convert dictionary to list
        embedding_list = []
        for card_id, embedding in embeddings.items():
            db_embedding = {
                'card_id': card_id,
                'embedding': embedding.tolist(),  # Convert numpy array to list
                'updated_at': time.strftime('%Y-%m-%d %H:%M:%S')
            }
            embedding_list.append(db_embedding)

        # Insert in batches
        batch_size = 50  # Smaller batch size due to larger payload
        total_batches = (len(embedding_list) + batch_size - 1) // batch_size

        for i in tqdm(range(0, len(embedding_list), batch_size), desc="Uploading card embedding batches", total=total_batches):
            batch = embedding_list[i:i+batch_size]

            try:
                # Upsert data
                result = self.supabase.table('mtg_card_embeddings').upsert(batch).execute()

                if hasattr(result, 'error') and result.error:
                    print(f"Error in batch {i//batch_size + 1}: {result.error}")
            except Exception as e:
                print(f"Failed to upload card embedding batch {i//batch_size + 1}: {e}")

    def supplement_card_data(self) -> Dict:
        """Add missing cards to existing card data"""
        print("Checking for missing cards to add...")

        # Count existing cards
        existing_count = len(self.card_dict)
        print(f"Currently have {existing_count} cards")

        # Get all sets
        all_sets = self.fetch_all_sets()
        print(f"Found {len(all_sets)} sets")

        # Create a set of existing card IDs for faster lookup
        existing_ids = set(self.card_dict.keys())

        # Track new cards
        new_cards = {}
        new_count = 0

        # Process each set
        for set_data in all_sets:
            set_code = set_data.get('code')
            set_name = set_data.get('name')
            search_uri = set_data.get('search_uri')

            if not search_uri:
                continue

            print(f"Checking {set_name} ({set_code}) for new cards...")

            # Use the search URI to get all cards in the set
            url = search_uri
            set_new_cards = 0

            while url:
                # Add delay to avoid rate limiting
                time.sleep(0.1)

                try:
                    response = requests.get(url)

                    # Handle rate limiting
                    if response.status_code == 429:
                        retry_after = int(response.headers.get('Retry-After', 1))
                        print(f"Rate limited. Waiting {retry_after} seconds...")
                        time.sleep(retry_after)
                        response = requests.get(url)

                    if response.status_code != 200:
                        print(f"Error fetching data: {response.status_code}")
                        break

                    data = response.json()

                    # Check if cards are already in our data
                    for card in data.get('data', []):
                        card_id = card.get('id')

                        # Skip if no ID or already have this card
                        if not card_id or card_id in existing_ids:
                            continue

                        # Add the new card
                        new_cards[card_id] = {
                            'id': card_id,
                            'name': card.get('name', ''),
                            'type_line': card.get('type_line', ''),
                            'oracle_text': card.get('oracle_text', ''),
                            'mana_cost': card.get('mana_cost', ''),
                            'cmc': card.get('cmc', 0),
                            'color_identity': card.get('color_identity', []),
                            'keywords': card.get('keywords', []),
                            'image_uris': card.get('image_uris', {}),
                            'legalities': card.get('legalities', {}),
                            'prices': card.get('prices', {}),
                            'rarity': card.get('rarity', '')
                        }
                        set_new_cards += 1
                        new_count += 1

                    # Check for next page
                    url = data.get('next_page')

                except Exception as e:
                    print(f"Error processing set {set_code}: {e}")
                    break

            if set_new_cards > 0:
                print(f"  Added {set_new_cards} new cards from {set_name}")

        # Add new cards to existing data
        self.card_dict.update(new_cards)

        print(f"Added {new_count} new cards. Total: {len(self.card_dict)}")

        # Save to Supabase
        if self.use_supabase and new_cards:
            self._save_cards_to_supabase(new_cards)

        # Save updated data locally
        with open(f"{self.data_path}/card_data.json", 'w') as f:
            json.dump(self.card_dict, f)

        return self.card_dict

    def categorize_cards(self) -> Dict:
        """Categorize cards by various attributes for easier filtering"""
        print("Categorizing cards...")

        categories = {
            'color_identity': {},
            'creature_types': {},
            'mana_value': {},
            'keywords': {},
            'price_category': {},
            'legendary_creatures': []
        }

        # Extract creature types pattern
        creature_type_pattern = re.compile(r"(Human|Elf|Goblin|Zombie|Dragon|Angel|Demon|Vampire|Merfolk|Beast|Elemental|Wizard|Warrior|Soldier|Rogue|Cleric|Druid|Knight|Artificer|Shaman|Giant|Dinosaur|Spider|Snake|Bird|Cat|Dog|Wolf|Bear|Insect|Fish|Crab|Horror|Spirit|God|Faerie)")

        for card_id, card_info in tqdm(self.card_dict.items()):
            # Categorize by color identity
            identity = ''.join(sorted(card_info.get('color_identity', [])))
            identity = identity if identity else 'Colorless'

            if identity not in categories['color_identity']:
                categories['color_identity'][identity] = []
            categories['color_identity'][identity].append(card_id)

            # Categorize by mana value
            cmc = card_info.get('cmc', 0)
            cmc_category = None

            if cmc == 0: cmc_category = '0'
            elif cmc <= 2: cmc_category = '1-2'
            elif cmc <= 4: cmc_category = '3-4'
            elif cmc <= 6: cmc_category = '5-6'
            else: cmc_category = '7+'

            if cmc_category not in categories['mana_value']:
                categories['mana_value'][cmc_category] = []
            categories['mana_value'][cmc_category].append(card_id)

            # Categorize by keywords
            for keyword in card_info.get('keywords', []):
                if keyword not in categories['keywords']:
                    categories['keywords'][keyword] = []
                categories['keywords'][keyword].append(card_id)

            # Categorize by price
            price_category = self._determine_price_category(card_id)
            if price_category not in categories['price_category']:
                categories['price_category'][price_category] = []
            categories['price_category'][price_category].append(card_id)

            # Check if it's a legendary creature
            type_line = card_info.get('type_line', '').lower()
            if 'legendary' in type_line and 'creature' in type_line:
                categories['legendary_creatures'].append(card_id)

            # Extract creature types
            oracle_text = card_info.get('oracle_text', '')
            type_line = card_info.get('type_line', '')
            combined_text = f"{oracle_text} {type_line}"

            matches = creature_type_pattern.findall(combined_text)
            for creature_type in matches:
                if creature_type not in categories['creature_types']:
                    categories['creature_types'][creature_type] = []
                categories['creature_types'][creature_type].append(card_id)

        # Save to Supabase
        if self.use_supabase:
            self._save_categories_to_supabase(categories)

        # Save locally as well
        with open(f"{self.data_path}/card_categories.json", 'w') as f:
            json.dump(categories, f)

        return categories

    def _save_categories_to_supabase(self, categories: Dict) -> None:
        """Save card categories to Supabase"""
        print("Saving card categories to Supabase...")

        # Save legendary creatures
        legendary_creatures = [{'card_id': card_id} for card_id in categories['legendary_creatures']]

        try:
            # First clean out old data
            self.supabase.table('mtg_legendary_creatures').delete().execute()

            # Insert in batches
            batch_size = 100
            for i in range(0, len(legendary_creatures), batch_size):
                batch = legendary_creatures[i:i+batch_size]
                self.supabase.table('mtg_legendary_creatures').insert(batch).execute()

            print(f"Saved {len(legendary_creatures)} legendary creatures")
        except Exception as e:
            print(f"Error saving legendary creatures: {e}")

        # Save color identity categorizations
        color_identity_records = []
        for identity, card_ids in categories['color_identity'].items():
            for card_id in card_ids:
                color_identity_records.append({
                    'card_id': card_id,
                    'color_identity': identity
                })

        try:
            # First clean out old data
            self.supabase.table('mtg_color_identity').delete().execute()

            # Insert in batches
            batch_size = 100
            for i in range(0, len(color_identity_records), batch_size):
                batch = color_identity_records[i:i+batch_size]
                self.supabase.table('mtg_color_identity').insert(batch).execute()

            print(f"Saved {len(color_identity_records)} color identity records")
        except Exception as e:
            print(f"Error saving color identity records: {e}")

        # Save price categories
        price_category_records = []
        for category, card_ids in categories['price_category'].items():
            for card_id in card_ids:
                price_category_records.append({
                    'card_id': card_id,
                    'price_category': category
                })

        try:
            # First clean out old data
            self.supabase.table('mtg_price_categories').delete().execute()

            # Insert in batches
            batch_size = 100
            for i in range(0, len(price_category_records), batch_size):
                batch = price_category_records[i:i+batch_size]
                self.supabase.table('mtg_price_categories').insert(batch).execute()

            print(f"Saved {len(price_category_records)} price category records")
        except Exception as e:
            print(f"Error saving price category records: {e}")

    def _determine_price_category(self, card_id: str) -> str:
        """Determine the price category for a card"""
        price_info = self.price_data.get(card_id, {})
        usd_price = 0

        if price_info.get('usd'):
            try:
                usd_price = float(price_info['usd'])
            except (ValueError, TypeError):
                usd_price = 0

        if usd_price == 0:
            return 'Unknown'
        elif usd_price < 1:
            return 'Budget'
        elif usd_price < 5:
            return 'Affordable'
        elif usd_price < 20:
            return 'Moderate'
        elif usd_price < 50:
            return 'Premium'
        else:
            return 'High-End'

    def load_data(self) -> bool:
        """Load existing data from disk in Google Drive"""
        try:
            print(f"Trying to load data from {self.data_path}")

            with open(f"{self.data_path}/card_data.json", 'r') as f:
                self.card_dict = json.load(f)
            print(f"Loaded {len(self.card_dict)} cards from disk")

            with open(f"{self.data_path}/price_data.json", 'r') as f:
                self.price_data = json.load(f)
            print(f"Loaded price data for {len(self.price_data)} cards from disk")

            with open(f"{self.data_path}/card_embeddings.pkl", 'rb') as f:
                self.embeddings = pickle.load(f)
            print(f"Loaded embeddings for {len(self.embeddings)} cards from disk")

            with open(f"{self.data_path}/price_embeddings.pkl", 'rb') as f:
                self.price_embeddings = pickle.load(f)
            print(f"Loaded price embeddings for {len(self.price_embeddings)} cards from disk")

            return True
        except FileNotFoundError as e:
            print(f"Data files not found: {e}")
            print("Please run the data collection process.")
            return False
        except Exception as e:
            print(f"Error loading data: {e}")
            return False

    def load_data_from_supabase(self) -> bool:
        """Load existing data from Supabase"""
        if not self.use_supabase:
            print("Supabase integration is disabled")
            return False

        try:
            print("Loading data from Supabase...")

            # Load card data
            response = self.supabase.table('mtg_cards').select('*').execute()
            if hasattr(response, 'data'):
                card_data = response.data

                # Convert to dictionary format
                self.card_dict = {}
                for card in card_data:
                    card_id = card.get('id')
                    if card_id:
                        # Convert JSON strings back to objects
                        for field in ['color_identity', 'keywords', 'image_uris', 'legalities', 'prices']:
                            if card.get(field) and isinstance(card[field], str):
                                try:
                                    card[field] = json.loads(card[field])
                                except json.JSONDecodeError:
                                    card[field] = {}

                        self.card_dict[card_id] = card

                print(f"Loaded {len(self.card_dict)} cards from Supabase")

            # Load price data
            response = self.supabase.table('mtg_prices').select('*').execute()
            if hasattr(response, 'data'):
                price_data = response.data

                # Convert to dictionary format
                self.price_data = {}
                for price in price_data:
                    card_id = price.get('card_id')
                    if card_id:
                        self.price_data[card_id] = {
                            'name': price.get('name', ''),
                            'usd': price.get('usd'),
                            'usd_foil': price.get('usd_foil'),
                            'usd_etched': price.get('usd_etched'),
                            'eur': price.get('eur'),
                            'tix': price.get('tix')
                        }

                print(f"Loaded price data for {len(self.price_data)} cards from Supabase")

            # Load card embeddings
            response = self.supabase.table('mtg_card_embeddings').select('*').execute()
            if hasattr(response, 'data'):
                embedding_data = response.data

                # Convert to dictionary format
                self.embeddings = {}
                for embed in embedding_data:
                    card_id = embed.get('card_id')
                    embedding = embed.get('embedding')
                    if card_id and embedding:
                        self.embeddings[card_id] = np.array(embedding)

                print(f"Loaded embeddings for {len(self.embeddings)} cards from Supabase")

            # Load price embeddings
            response = self.supabase.table('mtg_price_embeddings').select('*').execute()
            if hasattr(response, 'data'):
                price_embedding_data = response.data

                # Convert to dictionary format
                self.price_embeddings = {}
                for embed in price_embedding_data:
                    card_id = embed.get('card_id')
                    embedding = embed.get('embedding')
                    if card_id and embedding:
                        self.price_embeddings[card_id] = np.array(embedding)

                print(f"Loaded price embeddings for {len(self.price_embeddings)} cards from Supabase")

            return True

        except Exception as e:
            print(f"Error loading data from Supabase: {e}")
            print("Falling back to local data...")
            return self.load_data()

    def search_cards_by_embeddings(self, query_text: str, n: int = 10,
                                  price_filter: Optional[str] = None) -> List[Dict]:
        """Search for cards similar to the query text with optional price filtering"""
        # Encode the query
        query_embedding = self.model.encode([query_text])

        # Calculate similarities
        similarities = {}
        for card_id, embedding in self.embeddings.items():
            # Skip if price filter is active and card doesn't match
            if price_filter and self._determine_price_category(card_id) != price_filter:
                continue

            # Calculate cosine similarity
            similarity = np.dot(query_embedding, embedding) / (
                np.linalg.norm(query_embedding) * np.linalg.norm(embedding)
            )
            similarities[card_id] = similarity

        # Sort by similarity and get top n
        top_cards = sorted(similarities.items(), key=lambda x: x[1], reverse=True)[:n]

        # Return full card data
        results = []
        for card_id, similarity in top_cards:
            card_data = self.card_dict[card_id].copy()
            card_data['similarity'] = similarity
            card_data['price_category'] = self._determine_price_category(card_id)

            # Add actual price
            price_info = self.price_data.get(card_id, {})
            card_data['usd_price'] = price_info.get('usd')

            results.append(card_data)

        return results

    def search_cards_by_embeddings_supabase(self, query_text: str, n: int = 10,
                                          price_filter: Optional[str] = None) -> List[Dict]:
        """Search for cards using Supabase's vector search capabilities (if available)"""
        if not self.use_supabase:
            print("Supabase integration is disabled, using local search instead")
            return self.search_cards_by_embeddings(query_text, n, price_filter)

        try:
            # Encode the query
            query_embedding = self.model.encode([query_text])[0].tolist()

            # Construct the SQL query with vector similarity search
            # Note: This requires pgvector extension to be enabled in Supabase
            select_query = self.supabase.table('mtg_card_embeddings')

            # Join with cards table
            select_query = select_query.select(
                'mtg_card_embeddings.card_id',
                'mtg_cards.name',
                'mtg_cards.type_line',
                'mtg_cards.oracle_text',
                'mtg_cards.color_identity',
                'mtg_cards.image_uris',
                'mtg_prices.usd'
            ).eq('mtg_card_embeddings.card_id', 'mtg_cards.id')

            # Add price filter if needed
            if price_filter:
                select_query = select_query.eq('mtg_price_categories.price_category', price_filter)

            # Add vector similarity calculation and ordering
            # Note: This is a placeholder - actual implementation depends on Supabase's vector support
            # query_param = {'embedding': query_embedding}
            # select_query = select_query.rpc('match_embeddings', query_param)

            # Execute query
            response = select_query.limit(n).execute()

            if hasattr(response, 'data'):
                results = []
                for item in response.data:
                    # Convert JSON strings back to objects
                    if 'color_identity' in item and isinstance(item['color_identity'], str):
                        item['color_identity'] = json.loads(item['color_identity'])
                    if 'image_uris' in item and isinstance(item['image_uris'], str):
                        item['image_uris'] = json.loads(item['image_uris'])

                    # Add price category
                    item['price_category'] = self._determine_price_category_from_price(item.get('usd', 0))

                    results.append(item)

                return results

            # Fall back to local search if no results or error
            print("No results from Supabase, falling back to local search")
            return self.search_cards_by_embeddings(query_text, n, price_filter)

        except Exception as e:
            print(f"Error searching with Supabase: {e}")
            print("Falling back to local search")
            return self.search_cards_by_embeddings(query_text, n, price_filter)

    def _determine_price_category_from_price(self, price: Union[str, float, None]) -> str:
        """Determine price category from a price value"""
        if price is None or price == 'null':
            return 'Unknown'

        # Convert to float if string
        if isinstance(price, str):
            try:
                price = float(price)
            except ValueError:
                return 'Unknown'

        # Categorize
        if price == 0:
            return 'Unknown'
        elif price < 1:
            return 'Budget'
        elif price < 5:
            return 'Affordable'
        elif price < 20:
            return 'Moderate'
        elif price < 50:
            return 'Premium'
        else:
            return 'High-End'

    def get_legendary_creatures(self,
                               color_identity: Optional[str] = None,
                               max_price: Optional[float] = None) -> List[Dict]:
        """Get all legendary creatures with optional filters"""
        results = []

        for card_id, card_info in self.card_dict.items():
            type_line = card_info.get('type_line', '').lower()

            # Skip if not a legendary creature
            if not ('legendary' in type_line and 'creature' in type_line):
                continue

            # Filter by color identity if specified
            if color_identity:
                card_colors = ''.join(sorted(card_info.get('color_identity', [])))
                if color_identity != card_colors:
                    continue

            # Filter by price if specified
            if max_price is not None:
                price_info = self.price_data.get(card_id, {})
                if price_info.get('usd'):
                    try:
                        usd_price = float(price_info['usd'])
                        if usd_price > max_price:
                            continue
                    except (ValueError, TypeError):
                        pass

            # Add to results
            commander_data = {
                'id': card_id,
                'name': card_info.get('name', ''),
                'color_identity': card_info.get('color_identity', []),
                'type_line': card_info.get('type_line', ''),
                'oracle_text': card_info.get('oracle_text', ''),
                'mana_cost': card_info.get('mana_cost', ''),
                'cmc': card_info.get('cmc', 0),
                'image_uri': card_info.get('image_uris', {}).get('small', ''),
                'price_category': self._determine_price_category(card_id),
                'usd_price': self.price_data.get(card_id, {}).get('usd')
            }

            results.append(commander_data)

        # Sort by name
        results.sort(key=lambda x: x['name'])

        return results

    def get_legendary_creatures_supabase(self,
                                        color_identity: Optional[str] = None,
                                        max_price: Optional[float] = None) -> List[Dict]:
        """Get legendary creatures using Supabase query"""
        if not self.use_supabase:
            print("Supabase integration is disabled, using local query instead")
            return self.get_legendary_creatures(color_identity, max_price)

        try:
            # Start with legendary creatures table
            query = self.supabase.table('mtg_legendary_creatures')

            # Join with cards and price tables
            query = query.select(
                'mtg_legendary_creatures.card_id',
                'mtg_cards.name',
                'mtg_cards.type_line',
                'mtg_cards.oracle_text',
                'mtg_cards.mana_cost',
                'mtg_cards.cmc',
                'mtg_cards.color_identity',
                'mtg_cards.image_uris',
                'mtg_prices.usd'
            ).eq('mtg_legendary_creatures.card_id', 'mtg_cards.id')

            # Add color identity filter if specified
            if color_identity:
                query = query.eq('mtg_color_identity.color_identity', color_identity)

            # Add price filter if specified
            if max_price is not None:
                query = query.lte('mtg_prices.usd', max_price)

            # Execute query
            response = query.execute()

            if hasattr(response, 'data'):
                results = []
                for item in response.data:
                    # Convert JSON strings back to objects
                    if 'color_identity' in item and isinstance(item['color_identity'], str):
                        item['color_identity'] = json.loads(item['color_identity'])
                    if 'image_uris' in item and isinstance(item['image_uris'], str):
                        item['image_uris'] = json.loads(item['image_uris'])

                    # Extract small image URI
                    item['image_uri'] = item.get('image_uris', {}).get('small', '')

                    # Add price category
                    item['price_category'] = self._determine_price_category_from_price(item.get('usd', 0))
                    item['usd_price'] = item.get('usd')

                    results.append(item)

                # Sort by name
                results.sort(key=lambda x: x['name'])
                return results

            # Fall back to local query if no results or error
            print("No results from Supabase, falling back to local query")
            return self.get_legendary_creatures(color_identity, max_price)

        except Exception as e:
            print(f"Error querying with Supabase: {e}")
            print("Falling back to local query")
            return self.get_legendary_creatures(color_identity, max_price)

    def get_image_urls_for_deck_generator(self):
        """Extract image URLs by card name for use in deck visualization"""
        card_images = {}

        for card_id, card_info in self.card_dict.items():
            card_name = card_info.get('name')
            if not card_name:
                continue

            # Handle dual-faced cards
            if 'card_faces' in card_info and 'image_uris' not in card_info:
                # Use front face image
                image_url = card_info.get('card_faces', [{}])[0].get('image_uris', {}).get('normal')
            else:
                # Get the normal image URL
                image_url = card_info.get('image_uris', {}).get('normal')

            if image_url:
                card_images[card_name] = image_url

        # Save to disk for efficient future use
        with open(f"{self.data_path}/card_images.json", 'w') as f:
            json.dump(card_images, f)

        # Save to Supabase if enabled
        if self.use_supabase:
            self._save_card_images_to_supabase(card_images)

        return card_images

    def _save_card_images_to_supabase(self, card_images: Dict) -> None:
        """Save card images to Supabase"""
        print("Saving card images to Supabase...")

        # Convert dictionary to list
        image_list = []
        for card_name, image_url in card_images.items():
            db_image = {
                'card_name': card_name,
                'image_url': image_url,
                'updated_at': time.strftime('%Y-%m-%d %H:%M:%S')
            }
            image_list.append(db_image)

        # Insert in batches
        batch_size = 100
        total_batches = (len(image_list) + batch_size - 1) // batch_size

        for i in tqdm(range(0, len(image_list), batch_size), desc="Uploading image URL batches", total=total_batches):
            batch = image_list[i:i+batch_size]

            try:
                # Upsert data
                result = self.supabase.table('mtg_card_images').upsert(batch).execute()

                if hasattr(result, 'error') and result.error:
                    print(f"Error in batch {i//batch_size + 1}: {result.error}")
            except Exception as e:
                print(f"Failed to upload image URL batch {i//batch_size + 1}: {e}")

    def run_full_pipeline(self) -> None:
        """Run the full data processing pipeline"""
        self.fetch_all_cards_by_set()
        self.extract_price_data()
        self.create_card_embeddings()
        self.create_price_embeddings()
        self.categorize_cards()
        self.get_image_urls_for_deck_generator()
        print("Full pipeline completed successfully!")

# Method to integrate with the existing deck generator code
def integrate_with_deck_generator(card_embedder, existing_card_dict):
    """
    Integrate price data with existing deck generator system

    Args:
        card_embedder: The MTGCardEmbedder instance
        existing_card_dict: The existing card dictionary from the deck generator

    Returns:
        Dict: Price data keyed by card name
    """
    print("Integrating price data with deck generator...")
    price_data_by_name = {}

    # Create a reverse lookup from card ID to name
    id_to_name = {}
    for card_id, card_info in card_embedder.card_dict.items():
        id_to_name[card_id] = card_info.get('name', '')

    # Create price data dictionary keyed by card name
    for card_id, price_info in card_embedder.price_data.items():
        card_name = id_to_name.get(card_id)
        if card_name:
            price_data_by_name[card_name] = {
                'usd': price_info.get('usd'),
                'usd_foil': price_info.get('usd_foil'),
                'usd_etched': price_info.get('usd_etched'),
                'eur': price_info.get('eur'),
                'tix': price_info.get('tix'),
                'price_category': card_embedder._determine_price_category(card_id)
            }

    # Save combined price data to Colab file
    with open('/content/mtg_price_data.json', 'w') as f:
        json.dump(price_data_by_name, f)

    print(f"Saved price data for {len(price_data_by_name)} cards")
    return price_data_by_name

# Example usage for Google Colab
if __name__ == "__main__":
    # Check if running in Colab
    try:
        import google.colab
        IS_COLAB = True
    except:
        IS_COLAB = False

    if IS_COLAB:
        print("Running in Google Colab environment")

        # Initialize the card system with Google Drive path and Supabase enabled
        card_system = MTGCardEmbedder(data_path="/content/drive/MyDrive/MTGData", use_supabase=True)

        # Try to load data from Supabase first, fall back to local if needed
        if not card_system.load_data_from_supabase() and not card_system.load_data():
            # Run the full pipeline
            print("Data not found. Running full pipeline to collect card data...")
            card_system.run_full_pipeline()
        else:
            # Supplement with any missing cards
            card_system.supplement_card_data()

            # Update other data based on new cards
            card_system.extract_price_data()
            card_system.create_card_embeddings()
            card_system.create_price_embeddings()
            card_system.categorize_cards()
            card_system.get_image_urls_for_deck_generator()

        # Example search
        results = card_system.search_cards_by_embeddings("dragon tribal commander", n=5)
        for card in results:
            print(f"{card['name']} - {card['price_category']} - {card['usd_price']}")

        # Example commander list
        commanders = card_system.get_legendary_creatures(max_price=10.0)
        print(f"Found {len(commanders)} budget commanders")
    else:
        print("Not running in Google Colab environment")

import json
import os
import time
from tqdm import tqdm
from dotenv import load_dotenv
from supabase import create_client
from google.colab import drive

def process_color_identity_and_commanders():
    """
    Process and save specifically the color identity information and legendary creatures
    to Supabase using existing card data, without regenerating embeddings.
    """
    print("Starting targeted processing of color identity and legendary creatures")

    # Mount Google Drive if not already mounted
    try:
        drive.mount('/content/drive', force_remount=False)
        print("Google Drive mounted successfully")
    except:
        print("Google Drive already mounted or could not be mounted")

    # Set data path
    data_path = "/content/drive/MyDrive/MTGData"

    # Load environment variables
    env_path = f"{data_path}/.env"
    if os.path.exists(env_path):
        load_dotenv(env_path)
        print("Loaded environment variables")
    else:
        print("No .env file found. Creating one...")
        os.makedirs(data_path, exist_ok=True)

        # Get Supabase credentials
        from getpass import getpass
        supabase_url = input("Enter your Supabase URL (default: https://hvsbfeyufrzmohzxsbcq.supabase.co): ") or "https://hvsbfeyufrzmohzxsbcq.supabase.co"
        supabase_key = getpass("Enter your Supabase API key: ")

        # Save to .env file
        with open(env_path, 'w') as f:
            f.write(f"SUPABASE_URL={supabase_url}\n")
            f.write(f"SUPABASE_KEY={supabase_key}\n")

        print(f"Created .env file at {env_path}")
        load_dotenv(env_path)

    # Initialize Supabase client
    supabase_url = os.getenv('SUPABASE_URL')
    supabase_key = os.getenv('SUPABASE_KEY')

    if not supabase_key:
        print("ERROR: Supabase key not found in environment variables")
        return

    try:
        supabase = create_client(supabase_url, supabase_key)
        print("Supabase client initialized successfully")
    except Exception as e:
        print(f"Error initializing Supabase: {e}")
        return

    # Load existing card data
    card_data_path = f"{data_path}/card_data.json"
    if not os.path.exists(card_data_path):
        print(f"ERROR: Card data file not found at {card_data_path}")
        print("Please run the full pipeline first to collect card data")
        return

    with open(card_data_path, 'r') as f:
        card_dict = json.load(f)

    print(f"Loaded {len(card_dict)} cards from file")

    # Process and save color identity
    def process_and_save_color_identity():
        """Process and save color identity information"""
        print("\n--- Processing Color Identity ---")

        # Extract color identities from card data
        color_identity_dict = {}

        for card_id, card_info in tqdm(card_dict.items(), desc="Extracting color identities"):
            identity = ''.join(sorted(card_info.get('color_identity', [])))
            identity = identity if identity else 'Colorless'

            if identity not in color_identity_dict:
                color_identity_dict[identity] = []
            color_identity_dict[identity].append(card_id)

        print(f"Found {len(color_identity_dict)} different color identities")

        # Save to Supabase
        print("Saving color identity information to Supabase...")

        # Convert to list of records
        color_identity_records = []
        for identity, card_ids in color_identity_dict.items():
            for card_id in card_ids:
                color_identity_records.append({
                    'card_id': card_id,
                    'color_identity': identity
                })

        try:
            # First clean out old data with a WHERE clause (to satisfy Supabase requirements)
            supabase.table('mtg_color_identity').delete().neq('card_id', 'no-match').execute()
            print("Cleared existing color identity data")

            # Insert in batches
            batch_size = 100
            total_batches = (len(color_identity_records) + batch_size - 1) // batch_size

            for i in tqdm(range(0, len(color_identity_records), batch_size), desc="Uploading color identity records", total=total_batches):
                batch = color_identity_records[i:i+batch_size]
                supabase.table('mtg_color_identity').insert(batch).execute()

            print(f"Saved {len(color_identity_records)} color identity records")
        except Exception as e:
            print(f"Error saving color identity records: {e}")

        return color_identity_dict

    # Process legendary creatures
    def process_and_save_legendary_creatures():
        """Process and save legendary creature information"""
        print("\n--- Processing Legendary Creatures ---")

        # Extract legendary creatures from card data
        legendary_creatures = []

        for card_id, card_info in tqdm(card_dict.items(), desc="Identifying legendary creatures"):
            type_line = card_info.get('type_line', '').lower()
            if 'legendary' in type_line and 'creature' in type_line:
                legendary_creatures.append(card_id)

        print(f"Found {len(legendary_creatures)} legendary creatures")

        # Save to Supabase
        print("Saving legendary creatures to Supabase...")

        # Convert to list of records
        legendary_creature_records = [{'card_id': card_id} for card_id in legendary_creatures]

        try:
            # First clean out old data with a WHERE clause
            supabase.table('mtg_legendary_creatures').delete().neq('card_id', 'no-match').execute()
            print("Cleared existing legendary creatures data")

            # Insert in batches
            batch_size = 100
            total_batches = (len(legendary_creature_records) + batch_size - 1) // batch_size

            for i in tqdm(range(0, len(legendary_creature_records), batch_size), desc="Uploading legendary creatures", total=total_batches):
                batch = legendary_creature_records[i:i+batch_size]
                supabase.table('mtg_legendary_creatures').insert(batch).execute()

            print(f"Saved {len(legendary_creature_records)} legendary creatures")
        except Exception as e:
            print(f"Error saving legendary creatures: {e}")

        return legendary_creatures

    # Main execution flow
    start_time = time.time()

    # Process color identity
    color_identity = process_and_save_color_identity()

    # Process legendary creatures
    legendary_creatures = process_and_save_legendary_creatures()

    end_time = time.time()
    elapsed_time = end_time - start_time

    # Print summary
    print("\n--- Processing Summary ---")
    print(f"Processed {len(card_dict)} cards")
    print(f"Processed {len(color_identity)} color identities")
    print(f"Identified {len(legendary_creatures)} legendary creatures")
    print(f"Total processing time: {elapsed_time:.2f} seconds ({elapsed_time/60:.2f} minutes)")

# Execute the script if run directly
if __name__ == "__main__":
    process_color_identity_and_commanders()

import json
import os
import time
from tqdm import tqdm
from dotenv import load_dotenv
from supabase import create_client
from google.colab import drive

def process_card_categories():
    """
    Process and save card categories to Supabase:
    - Color identity information
    - Legendary creatures list
    - Price categories

    Uses existing card data without regenerating embeddings.
    """
    print("Starting processing of card categories for Supabase")

    # Mount Google Drive if not already mounted
    try:
        drive.mount('/content/drive', force_remount=False)
        print("Google Drive mounted successfully")
    except:
        print("Google Drive already mounted or could not be mounted")

    # Set data path
    data_path = "/content/drive/MyDrive/MTGData"

    # Load environment variables
    env_path = f"{data_path}/.env"
    if os.path.exists(env_path):
        load_dotenv(env_path)
        print("Loaded environment variables")
    else:
        print("No .env file found. Creating one...")
        os.makedirs(data_path, exist_ok=True)

        # Get Supabase credentials
        from getpass import getpass
        supabase_url = input("Enter your Supabase URL (default: https://hvsbfeyufrzmohzxsbcq.supabase.co): ") or "https://hvsbfeyufrzmohzxsbcq.supabase.co"
        supabase_key = getpass("Enter your Supabase API key: ")

        # Save to .env file
        with open(env_path, 'w') as f:
            f.write(f"SUPABASE_URL={supabase_url}\n")
            f.write(f"SUPABASE_KEY={supabase_key}\n")

        print(f"Created .env file at {env_path}")
        load_dotenv(env_path)

    # Initialize Supabase client
    supabase_url = os.getenv('SUPABASE_URL')
    supabase_key = os.getenv('SUPABASE_KEY')

    if not supabase_key:
        print("ERROR: Supabase key not found in environment variables")
        return

    try:
        supabase = create_client(supabase_url, supabase_key)
        print("Supabase client initialized successfully")
    except Exception as e:
        print(f"Error initializing Supabase: {e}")
        return

    # Load existing card data
    card_data_path = f"{data_path}/card_data.json"
    if not os.path.exists(card_data_path):
        print(f"ERROR: Card data file not found at {card_data_path}")
        print("Please run the full pipeline first to collect card data")
        return

    with open(card_data_path, 'r') as f:
        card_dict = json.load(f)

    print(f"Loaded {len(card_dict)} cards from file")

    # Load price data for price categories
    price_data_path = f"{data_path}/price_data.json"
    if not os.path.exists(price_data_path):
        print(f"WARNING: Price data file not found at {price_data_path}")
        print("Will proceed without price categories")
        price_data = None
    else:
        with open(price_data_path, 'r') as f:
            price_data = json.load(f)
        print(f"Loaded price data for {len(price_data)} cards")

    # Process and save color identity
    def process_and_save_color_identity():
        """Process and save color identity information"""
        print("\n--- Processing Color Identity ---")

        # Extract color identities from card data
        color_identity_dict = {}

        for card_id, card_info in tqdm(card_dict.items(), desc="Extracting color identities"):
            identity = ''.join(sorted(card_info.get('color_identity', [])))
            identity = identity if identity else 'Colorless'

            if identity not in color_identity_dict:
                color_identity_dict[identity] = []
            color_identity_dict[identity].append(card_id)

        print(f"Found {len(color_identity_dict)} different color identities")

        # Save to Supabase
        print("Saving color identity information to Supabase...")

        # Convert to list of records
        color_identity_records = []
        for identity, card_ids in color_identity_dict.items():
            for card_id in card_ids:
                color_identity_records.append({
                    'id': card_id,
                    'color_identity': identity
                })

        try:
            # First clean out old data with a WHERE clause (to satisfy Supabase requirements)
            supabase.table('mtg_color_identity').delete().neq('card_id', 'no-match').execute()
            print("Cleared existing color identity data")

            # Insert in batches
            batch_size = 100
            total_batches = (len(color_identity_records) + batch_size - 1) // batch_size

            for i in tqdm(range(0, len(color_identity_records), batch_size), desc="Uploading color identity records", total=total_batches):
                batch = color_identity_records[i:i+batch_size]
                supabase.table('mtg_color_identity').insert(batch).execute()

            print(f"Saved {len(color_identity_records)} color identity records")
        except Exception as e:
            print(f"Error saving color identity records: {e}")

        return color_identity_dict

    # Process legendary creatures
    def process_and_save_legendary_creatures():
        """Process and save legendary creature information"""
        print("\n--- Processing Legendary Creatures ---")

        # Extract legendary creatures from card data
        legendary_creatures = []

        for card_id, card_info in tqdm(card_dict.items(), desc="Identifying legendary creatures"):
            type_line = card_info.get('type_line', '').lower()
            if 'legendary' in type_line and 'creature' in type_line:
                legendary_creatures.append(card_id)

        print(f"Found {len(legendary_creatures)} legendary creatures")

        # Save to Supabase
        print("Saving legendary creatures to Supabase...")

        # Convert to list of records
        legendary_creature_records = [{'card_id': card_id} for card_id in legendary_creatures]

        try:
            # First clean out old data with a WHERE clause
            supabase.table('mtg_legendary_creatures').delete().neq('card_id', 'no-match').execute()
            print("Cleared existing legendary creatures data")

            # Insert in batches
            batch_size = 100
            total_batches = (len(legendary_creature_records) + batch_size - 1) // batch_size

            for i in tqdm(range(0, len(legendary_creature_records), batch_size), desc="Uploading legendary creatures", total=total_batches):
                batch = legendary_creature_records[i:i+batch_size]
                supabase.table('mtg_legendary_creatures').insert(batch).execute()

            print(f"Saved {len(legendary_creature_records)} legendary creatures")
        except Exception as e:
            print(f"Error saving legendary creatures: {e}")

        return legendary_creatures

    # Process price categories
    def process_and_save_price_categories():
        """Process and save price category information"""
        print("\n--- Processing Price Categories ---")

        if not price_data:
            print("ERROR: Price data not available - skipping price categories")
            return None

        # Function to determine price category
        def determine_price_category(card_id):
            price_info = price_data.get(card_id, {})
            usd_price = 0

            if price_info.get('usd'):
                try:
                    usd_price = float(price_info['usd'])
                except (ValueError, TypeError):
                    usd_price = 0

            if usd_price == 0:
                return 'Unknown'
            elif usd_price < 1:
                return 'Budget'
            elif usd_price < 5:
                return 'Affordable'
            elif usd_price < 20:
                return 'Moderate'
            elif usd_price < 50:
                return 'Premium'
            else:
                return 'High-End'

        # Extract price categories
        price_category_dict = {
            'Unknown': [],
            'Budget': [],
            'Affordable': [],
            'Moderate': [],
            'Premium': [],
            'High-End': []
        }

        for card_id in tqdm(card_dict.keys(), desc="Categorizing card prices"):
            category = determine_price_category(card_id)
            price_category_dict[category].append(card_id)

        # Count cards in each category
        category_counts = {cat: len(cards) for cat, cards in price_category_dict.items()}
        print("Price category distribution:")
        for category, count in category_counts.items():
            print(f"  {category}: {count} cards")

        # Save to Supabase
        print("Saving price categories to Supabase...")

        # Convert to list of records
        price_category_records = []
        for category, card_ids in price_category_dict.items():
            for card_id in card_ids:
                price_category_records.append({
                    'card_id': card_id,
                    'price_category': category
                })

        try:
            # First clean out old data with a WHERE clause
            supabase.table('mtg_price_categories').delete().neq('card_id', 'no-match').execute()
            print("Cleared existing price category data")

            # Insert in batches
            batch_size = 100
            total_batches = (len(price_category_records) + batch_size - 1) // batch_size

            for i in tqdm(range(0, len(price_category_records), batch_size), desc="Uploading price categories", total=total_batches):
                batch = price_category_records[i:i+batch_size]
                supabase.table('mtg_price_categories').insert(batch).execute()

            print(f"Saved {len(price_category_records)} price category records")
        except Exception as e:
            print(f"Error saving price categories: {e}")

        return price_category_dict

    # Main execution flow
    start_time = time.time()

    # Process color identity
    color_identity = process_and_save_color_identity()

    # Process legendary creatures
    legendary_creatures = process_and_save_legendary_creatures()

    # Process price categories
    price_categories = process_and_save_price_categories()

    end_time = time.time()
    elapsed_time = end_time - start_time

    # Print summary
    print("\n--- Processing Summary ---")
    print(f"Processed {len(card_dict)} cards")
    print(f"Processed {len(color_identity)} color identities")
    print(f"Identified {len(legendary_creatures)} legendary creatures")
    if price_categories:
        print(f"Categorized cards into {len(price_categories)} price categories")
    print(f"Total processing time: {elapsed_time:.2f} seconds ({elapsed_time/60:.2f} minutes)")

# Execute the script if run directly
if __name__ == "__main__":
    process_card_categories()