export interface BeginnerDeck {
  id: string;
  name: string;
  commander: string;
  colors: string[];
  bracket: number;
  plan: string;
  decklist: string;
  audience?: 'beginner' | 'practice';
  focusTags?: string[];
  keyCards?: string[];
  coachingNotes?: string[];
}

const BASIC_LANDS = new Set(['Plains', 'Island', 'Swamp', 'Mountain', 'Forest']);

function copies(count: number, name: string): string[] {
  return Array.from({ length: count }, () => `1 ${name}`);
}

function decklist(commander: string, cards: string[]): string {
  return ['Commander', `1 ${commander}`, 'Deck', ...cards].join('\n');
}

function oneOf(names: string[]): string[] {
  return names.map(name => `1 ${name}`);
}

export const CERTIFIED_GREEN_FILLER = [
  'Balduvian Bears',
  'Barbary Apes',
  'Bear Cub',
  'Brushstrider',
  'Canopy Spider',
  'Cylian Elf',
  'Elvish Archers',
  'Elvish Warrior',
  'Forest Bear',
  'Grappler Spider',
  'Greenwood Sentinel',
  'Grizzly Bears',
  'Kalonian Tusker',
  'Moon Sprite',
  'Runeclaw Bear',
  'Swordwise Centaur',
  'Terrain Elemental',
  'Underdark Basilisk',
  'Alpine Grizzly',
  'Centaur Courser',
  'Colossodon Yearling',
  'Elvish Ranger',
  'Gnarled Mass',
  'Gnottvold Recluse',
  'Goliath Beetle',
  'Gorilla Warrior',
  'Harrier Naga',
  'Hitchclaw Recluse',
  'Kraul Stinger',
  'Leatherback Baloth',
  'Mosscoat Goriak',
  'Nessian Courser',
  'Orazca Frillback',
  'Rib Cage Spider',
  'Spined Karok',
  'Sporecap Spider',
  'Tajuru Snarecaster',
  'Trained Armodon',
  'Axebane Beast',
  'Broodhunter Wurm',
  'Cloudcrown Oak',
] as const;

export const CERTIFIED_RED_FILLER = [
  'Crimson Kobolds',
  'Crookshank Kobolds',
  'Kobolds of Kher Keep',
  'Dwarven Trader',
  "Mons's Goblin Raiders",
  'Mountain Bandit',
  'Warship Scout',
  'Capital Guard',
  'Defiant Khenra',
  'Deranged Whelp',
  'Falkenrath Reaver',
  'Feral Maaka',
  'Goblin Assailant',
  'Goblin Bully',
  'Goblin Piker',
  'Goblin Striker',
  'Goblin Trailblazer',
  'Independent Troops',
  'Leopard-Spotted Jiao',
  'Nest Robber',
  'Roc Hunter',
  'Satyr Rambler',
  'Swab Goblin',
  'Balduvian Barbarians',
  'Bird Maiden',
  'Boggart Brute',
  'Breakneck Berserker',
  'Fearless Halberdier',
  'Frenzied Raptor',
  'Goblin Cavaliers',
  'Goblin Hero',
  'Goblin Roughrider',
  'Goblin Sky Raider',
  'Gore Swine',
  'Gray Ogre',
  'Hulking Bugbear',
  'Hurloon Minotaur',
  'Minotaur Warrior',
  'Nimble Birdsticker',
  'Onakke Ogre',
  'Pensive Minotaur',
  'Raging Bull',
  'Regathan Firecat',
] as const;

export const CERTIFIED_BLUE_FILLER = [
  'Aegis Turtle',
  'Aven Envoy',
  'Flying Men',
  'Fugitive Wizard',
  'Kraken Hatchling',
  'Merfolk of the Pearl Trident',
  'Mist-Cloaked Herald',
  'Shorecomber Crab',
  'Slither Blade',
  'Triton Shorestalker',
  'Triton Shorethief',
  'Wandering Ones',
  'Zephyr Sprite',
  'Bay Falcon',
  'Coral Eel',
  'Coral Merfolk',
  'Curio Vendor',
  'Flying Dolphin-Fish',
  'Jhessian Lookout',
  'Lumengrid Warden',
  'Maritime Guard',
  'Metathran Soldier',
  'Plated Seastrider',
  'Sea Eagle',
  'Seacoast Drake',
  'Seagraf Skaab',
  'Storm Crow',
  'Sworn Guardian',
  'Talas Merchant',
  'Talas Scout',
  'Vodalian Soldiers',
  'Wetland Sambar',
  'Winged Sliver',
  'Ancient Crab',
  'Armored Whirl Turtle',
  'Blind Phantasm',
  'Coral Commando',
  'Horned Turtle',
  'Naga Eternal',
  "Oko's Accomplices",
  'Phantom Warrior',
] as const;

export const CERTIFIED_BLUE_SPELLS = [
  'Divination',
  'Counsel of the Soratami',
  'Concentrate',
  'Quick Study',
  'Inspiration',
  'Think Twice',
  'Hieroglyphic Illumination',
  'Sleight of Hand',
  'Serum Visions',
  'Anticipate',
  'Curate',
  'Strategic Planning',
  'See Beyond',
  'Compulsive Research',
  'Frantic Search',
  'Peek',
  'Disperse',
  'Blink of an Eye',
  'Aetherize',
  "Jace's Ingenuity",
] as const;

export const BEGINNER_DECKS: BeginnerDeck[] = [
  {
    id: 'beginner-goreclaw-stompy',
    name: 'Green Big Creatures',
    commander: 'Goreclaw, Terror of Qal Sisma',
    colors: ['G'],
    bracket: 2,
    plan: 'Ramp, cast one large creature at a time, and attack.',
    decklist: decklist('Goreclaw, Terror of Qal Sisma', [
      ...copies(38, 'Forest'),
      ...copies(4, 'Forest'),
      '1 Sol Ring',
      '1 Arcane Signet',
      '1 Llanowar Elves',
      '1 Elvish Mystic',
      '1 Fyndhorn Elves',
      '1 Rampant Growth',
      "1 Kodama's Reach",
      '1 Cultivate',
      "1 Garruk's Uprising",
      '1 Rancor',
      '1 Return of the Wildspeaker',
      '1 Beast Within',
      '1 Reclamation Sage',
      '1 Acidic Slime',
      '1 Colossal Dreadmaw',
      '1 Terra Stomper',
      ...oneOf([...CERTIFIED_GREEN_FILLER]),
    ]),
  },
  {
    id: 'beginner-krenko-goblins',
    name: 'Red Goblin Swarm',
    commander: 'Krenko, Mob Boss',
    colors: ['R'],
    bracket: 2,
    plan: 'Make goblins, tap Krenko, and turn a wide board sideways.',
    decklist: decklist('Krenko, Mob Boss', [
      ...copies(38, 'Mountain'),
      ...copies(4, 'Mountain'),
      '1 Sol Ring',
      '1 Arcane Signet',
      '1 Lightning Bolt',
      '1 Abrade',
      '1 Chaos Warp',
      '1 Goblin Instigator',
      '1 Dragon Fodder',
      "1 Krenko's Command",
      '1 Hordeling Outburst',
      '1 Goblin Matron',
      '1 Goblin Warchief',
      '1 Goblin Chieftain',
      '1 Skirk Prospector',
      '1 Impact Tremors',
      ...oneOf([...CERTIFIED_RED_FILLER]),
    ]),
  },
  {
    id: 'beginner-talrand-spells',
    name: 'Blue Spell Practice',
    commander: 'Talrand, Sky Summoner',
    colors: ['U'],
    bracket: 2,
    plan: 'Cast small spells, make Drake tokens, and practice responding.',
    decklist: decklist('Talrand, Sky Summoner', [
      ...copies(38, 'Island'),
      ...copies(4, 'Island'),
      '1 Sol Ring',
      '1 Arcane Signet',
      '1 Sky Diamond',
      '1 Mind Stone',
      '1 Ponder',
      '1 Preordain',
      '1 Opt',
      '1 Brainstorm',
      '1 Consider',
      '1 Impulse',
      '1 Chart a Course',
      "1 Talrand's Invocation",
      '1 Counterspell',
      '1 Negate',
      '1 Unsummon',
      '1 Into the Roil',
      ...oneOf([...CERTIFIED_BLUE_SPELLS]),
      ...oneOf([...CERTIFIED_BLUE_FILLER].slice(0, 21)),
    ]),
  },
];

export const XENAGOS_PRACTICE_FOCUS_TAGS = [
  'burst mana',
  'tutor sequencing',
  'dragon ETB damage',
  'Xenagos combat math',
  'extra combat branches',
] as const;

export const XENAGOS_PRACTICE_KEY_CARDS = [
  'Xenagos, God of Revels',
  'Dracogenesis',
  'Terror of the Peaks',
  'Twinflame Tyrant',
  'Tooth and Nail',
  'Natural Order',
  "Green Sun's Zenith",
  'Anzrag, the Quake-Mole',
  'Hellkite Charger',
  'Savage Ventmaw',
  'Blacker Lotus',
] as const;

export const XENAGOS_PRACTICE_COACHING_NOTES = [
  'Check whether burst mana converts into a protected threat, tutor, or lethal combat branch this turn.',
  'Before committing Dracogenesis or a Terror line, identify the trigger order that changes damage output.',
  'During combat, decide which creature gets Xenagos before attack declarations and extra-combat commitments.',
] as const;

export const PRACTICE_DECKS: BeginnerDeck[] = [
  {
    id: 'practice-xenagos-dragons',
    name: 'Xenagos Dragon Lines',
    commander: 'Xenagos, God of Revels',
    colors: ['R', 'G'],
    bracket: 5,
    audience: 'practice',
    focusTags: [...XENAGOS_PRACTICE_FOCUS_TAGS],
    keyCards: [...XENAGOS_PRACTICE_KEY_CARDS],
    coachingNotes: [...XENAGOS_PRACTICE_COACHING_NOTES],
    plan: 'High-power dragon practice for fast mana, tutor sequencing, ETB damage storms, and Xenagos combat branches.',
    decklist: decklist('Xenagos, God of Revels', [
      '1 Allosaurus Shepherd',
      '1 Ancient Bronze Dragon',
      '1 Ancient Copper Dragon',
      '1 Anzrag, the Quake-Mole',
      '1 Arcane Signet',
      '1 Arid Mesa',
      '1 Backdraft Hellkite',
      '1 Balefire Dragon',
      '1 Beast Within',
      '1 Birds of Paradise',
      '1 Blacker Lotus',
      '1 Blasphemous Act',
      '1 Bloodstained Mire',
      '1 Cavern of Souls',
      '1 Cavern-Hoard Dragon',
      "1 Chandra's Ignition",
      '1 Chaos Warp',
      '1 Chrome Mox',
      '1 Deflecting Swat',
      '1 Delighted Halfling',
      '1 Disciple of Freyalise',
      '1 Dracogenesis',
      '1 Dragon Broodmother',
      "1 Dragonhawk, Fate's Tempest",
      '1 Dream Pillager',
      '1 Elvish Mystic',
      '1 Elvish Spirit Guide',
      '1 Exploration',
      ...copies(10, 'Forest'),
      '1 Fork',
      '1 Fyndhorn Elves',
      "1 Gaea's Cradle",
      '1 Gemstone Caverns',
      '1 Ghalta, Stampede Tyrant',
      '1 Goldspan Dragon',
      "1 Green Sun's Zenith",
      '1 Harrow',
      '1 Hellkite Charger',
      '1 Hellkite Tyrant',
      '1 Heroic Intervention',
      "1 Jeska's Will",
      '1 Jeweled Lotus',
      '1 Knollspine Dragon',
      '1 Kodama of the East Tree',
      '1 Last March of the Ents',
      '1 Leyline Tyrant',
      '1 Lotus Petal',
      '1 Mana Vault',
      '1 Misty Rainforest',
      ...copies(8, 'Mountain'),
      '1 Mox Diamond',
      '1 Natural Order',
      "1 Nature's Lore",
      '1 Neheb, the Eternal',
      '1 Nykthos, Shrine to Nyx',
      '1 Nyxbloom Ancient',
      '1 Old Gnawbone',
      '1 Prismatic Vista',
      '1 Reliquary Tower',
      '1 Return of the Wildspeaker',
      '1 Reverberate',
      "1 Rishkar's Expertise",
      '1 Sakura-Tribe Elder',
      '1 Savage Ventmaw',
      '1 Scalding Tarn',
      '1 Seething Song',
      '1 Selvala, Heart of the Wilds',
      '1 Shaman of Forgotten Ways',
      '1 Simian Spirit Guide',
      '1 Sol Ring',
      '1 Somberwald Sage',
      '1 Steel Hellkite',
      '1 Stomping Ground',
      '1 Taiga',
      '1 Terror of the Peaks',
      '1 Three Visits',
      "1 Tibalt's Trickery",
      '1 Tooth and Nail',
      '1 Traverse the Outlands',
      '1 Twinflame Tyrant',
      '1 Verdant Catacombs',
      '1 Windswept Heath',
      '1 Wooded Foothills',
    ]),
  },
];

export function decklistCardNames(deck: BeginnerDeck): string[] {
  return deck.decklist
    .split('\n')
    .map(line => line.trim())
    .filter(line => /^\d+\s+/.test(line))
    .map(line => line.replace(/^\d+\s+/, ''));
}

export function hasOnlyLegalBeginnerDuplicates(deck: BeginnerDeck): boolean {
  const seen = new Set<string>();
  for (const name of decklistCardNames(deck)) {
    if (BASIC_LANDS.has(name)) continue;
    if (seen.has(name)) return false;
    seen.add(name);
  }
  return true;
}
